version: "3.8"

services:
  web:
    build: .
    command: python /bookstore-app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/bookstore-app
    ports:
      - 8000:8000
    depends_on: 
      - db
  db:
    image: postgres
    # environment:
    #   - POSTGRES_DB=postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    # ports:
    #   - "5432:5432"
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data

